paper/paper.md
This PR should fix the [error](https://github.com/openjournals/joss-reviews/issues/1919#issuecomment-559604810) compiling the paper in the JOSS [review issue](https://github.com/openjournals/joss-reviews/issues/1919)
=> Fix indexing in affiliations

materials/forms.py, materials/static/materials/javascript/autoupdates.js, materials/templates/materials/add_data.html
This is a merge of Melosa's RIS Reference input implementation from her branch (risReference). 
Files updated:
- materials/forms.py
- materials/static/materials/javascript/autoupdates.js
- materials/templates/materials/add_data.html
=> Merge Melosa Rai's RIS Reference updates with master

materials/models.py
Disabled email notifications for updates on verified datasets.
=> Disabled email notifications for updates on verified datasets.

materials/admin.py, materials/signals.py, materials/templates/materials/add_data.html
This commit fixes integer only stoichiometries when fractionals are required.
=> Fixed integer only stoichiometries

materials/static/materials/javascript/autoupdates.js
Parse additional details (except author info) from RIS files.
Next step would be to get author information.
=> Parse additional details (except author info) from RIS files.

mainproject/__init__.py, requirements.txt
Added import for pymysql to reflect current status of HybriD3 server.
=> Added import for pymysql

materials/static/materials/javascript/autoupdates.js
Updated autoupdates.js to fill in authors from RIS file.
=> Updated autoupdates.js to fill in authors from RIS file.

materials/forms.py, materials/static/materials/javascript/autoupdates.js, materials/templates/materials/add_data.html
Added feature to parse refrences from .bib files.
=> Added feature to parse refrences from .bib files.

materials/static/materials/javascript/autoupdates.js
Added ISSN parsing for BIB files.
=> Added ISSN parsing for BIB files.

materials/forms.py, materials/templates/materials/search.html, materials/views.py
Added a bandgap filter for the search function.
=> Bandgap filter

materials/serializers.py
Updated serializers.py to add dimensionality and stoichiometry to systems API results
=> Updated serializers.py to add dimensionality and stoichiometry

materials/templates/materials/system.html
Updated system.html to display output better.
=> Updated system.html to display output better.

materials/serializers.py
Updated serializers.py to map dimensionality properly
=> Updated serializers.py to map dimensionality properly

materials/templates/materials/dataset_contents.html
Fixed dimensionality in datasets
=> Fixed dimensionality in datasets

materials/templates/materials/add_data.html
Removed dimensionality from add_data form for datasets.
=> Removed dimensionality from add_data form for datasets.

CHANGELOG.md
=> Bump up to v.3.2.0

materials/admin.py, materials/signals.py, materials/templates/materials/add_data.html
Updated additional bracket parsing for stoichiometry
=> Updated additional bracket parsing for stoichiometry

materials/serializers.py
Fixed reverse mapping of dimensionality in API
=> Fixed reverse mapping of dimensionality in API

materials/templates/materials/search.html, materials/views.py
Implemented DOI search function
=> Implemented DOI search function

.github/workflows/main.yml, doc/website.rst
Added files endpoint to web doc
=> Added files endpoint to web doc
